<?php
// /repo/app_a/php7_parse_url_empty.php

/**
 * Checks for query
 *
 * @param array $info : generated by parse_url()
 * @param string $message : passed by reference
 * @return bool $found : TRUE if query params found
 */
function checkQuery(array $info, string &$message)
{
    $found = isset($info['query']);
    if ($found) {
        parse_str($info['query'], $params);
        $what = var_export($params, TRUE) . "\n";
    } else {
        $what = "None\n";
    }
    $message .= 'Query   : ' . $what;
    return $found;
}

/**
 * Checks for fragment
 *
 * @param array $info : generated by parse_url()
 * @param string $message : passed by reference
 * @return bool $found : TRUE if fragment found
 */
function checkFragment(array $info, string &$message)
{
    $found = isset($info['fragment']);
    if ($found) {
        $what = $info['fragment'] . "\n";
    } else {
        $what = "None\n";
    }
    $message .= 'Fragment: ' . $what;
    return $found;
}

$data = [
    'https://api.unlikelysource.com/api?city=New%20York&postcode=10001',
    'https://phptraining.net/courses/cloudtechnician#database',
    'https://php-cl.com/courses?',
    'https://php-cl.com/courses?#'
];
foreach ($data as $url) {
    $message = '';
    $info = parse_url($url);
    checkQuery($info, $message);
    checkFragment($info, $message);
    echo "$url\n";
    echo $message;
}
